03_test4/test4/booktest/urls.py
# -*- coding:utf-8 -*-
# project_xxx\venv\Scripts python

'''
Author: Felix
WeiXin: AXiaShuBai
Email: xiashubai@gmail.com
Blog: https://blog.csdn.net/u011318077
GihHub: https://github.com/FelixZFB
Date: 2020/4/26 11:04
Desc:
'''

from django.conf.urls import url  #导入url函数
# 此处导入注意，由于test1和test2项目文件都标记为了source root
# 此处搜索booktest时候开始按循序先搜到了test1文件中的，然后导入的views就是test1中的
# 解决方法，不同项目尽量不要使用相同的名称，可以避免
# 折中方法：取消test1和test2的source root标记，
from booktest import views   #导入视图模块


# 应用urls文件中的配置时候注意：
# 1.严格匹配url地址的开头和结尾
# http://127.0.0.1:8000/index 从主页/之后开始匹配

urlpatterns = [
    # r表示一个纯字符串，^表示从字符串开头开始匹配
    # 第一个参数是一个正则表达式，第二个参数网址匹配成功后调用的处理方法
    url(r'^index$', views.index, name='index'), # 建立url和视图函数的联系，指定name参数，会自动将name的值和前面正则表达式中值进行动态匹配
    url(r'^index1$', views.index1), # 建立url和视图函数的联系
    url(r'^temp_tags$', views.temp_tags), # 模板标签使用
    url(r'^temp_inherit$', views.temp_inherit), # 模板继承
    url(r'^temp_escape$', views.temp_escape), # 模板转义
    url(r'^login$',views.login), # 显示登录界面
    url(r'^login_check$',views.login_check), # 用户校验
    url(r'^change_pwd$',views.change_pwd), # 显示修改密码页面
    url(r'^change_pwd_action$',views.change_pwd_action), # 修改密码处理
    url(r'^url_reverse$',views.url_reverse), # url反向解析网页，反向解析首页index
    url(r'^show_args/(\d+)/(\d+)$',views.show_args, name='show_args'), # 捕获位置参数
    url(r'^show_kwargs/(?P<num1>\d+)/(?P<num2>\d+)$',views.show_kwargs, name='show_kwargs'), # 捕获关键字参数，使用?P<num1>标明关键字为键为num1，就是正则表达式关键字分组
    url(r'^test_redirect$',views.test_redirect), # 视图使用url反向解析

    url(r'^static_test$',views.static_test), # 静态文件使用
    url(r'^index2$',views.index2), # 首页2
    url(r'^index3$',views.index3), # 首页3

    url(r'^pic_upload$', views.pic_upload), # 上传图片页面
    url(r'^pic_handle$', views.pic_handle), # 图片保存到文件夹中

    # 使用关键字分组，\d*表示匹配0个或多个
    url(r'^show_area/(?P<pageindex>\d*)$', views.show_area), # 显示地区信息
    url(r'^areas$', views.areas), # 省市区选择
    url(r'^prov$', views.prov), # 获取所有省级地区信息，返回json格式数据
    url(r'^city/(\d+)$', views.city), # 获取省下面市级信息
    url(r'^dis/(\d+)$', views.city), # 获取市下面县级信息，由于查询都是通过父级ID，查询方法和市级一样，使用同一个视图函数

]


# 注意：匹配时候urlpatterns中的表达式匹配网址提取的内容
# 并且从上往下匹配，匹配到一个就结束匹配
# 如果访问index2，我们用表达式中的index去匹配index2也是正确匹配的
# 因此我们需要严格匹配，匹配字符串开头^到结尾$,保证一致性

# 访问http://127.0.0.1:8000/index网页的步骤如下：
# 1.浏览器访问网址，django会自动提取地址/后面的 index
# 2.index 先到项目下的test4/urls中的urlpatterns中依次匹配
# 3.r''可以匹配任何内容，然后进booktest.urls中继续匹配
# 4.url(r'^index', views.index)匹配成功，然后调用的是视图views.index方法
# 5.返回index方法的结果，将内容显示在网页上

# 先启动服务器：python manage.py runserver
# 然后打开上面网页：http://127.0.0.1:8000/index

03_test4/test4/test4/urls.py
from django.contrib import admin
from django.urls import include, path

# 项目的urls文件，django2.0以前路径是使用的url，后面版本都使用path
urlpatterns = [
    path('admin/', admin.site.urls), # 配置项目，默认的后台管理请求
    # r表示一个纯字符串，''空白表示匹配任何内容，就可以匹配到index
    # 第一个参数是一个正则表达式，第二个参数是包含的应用的urls文件
    path(r'', include(('booktest.urls', 'booktest'), namespace='booktest')), # 包含booktest应用下的urls文件

    # path(r'^search/', include('haystack.urls', namespace='haystack')),
]


# 访问http://127.0.0.1:8000/index网页的步骤如下：
# 1.浏览器访问网址，django会自动提取地址/后面的 index
# 2.index 先到项目下的test4/urls中的urlpatterns中依次匹配
# 3.r''可以匹配任何内容，然后进booktest.urls中继续匹配
# 4.url(r'^index', views.index)匹配成功，然后调用的是视图views.index方法
# 5.返回index方法的结果，将内容显示在网页上


# 先启动服务器：python manage.py runserver
# 然后打开上面网页：http://127.0.0.1:8000/index

03_test4/test4/booktest/models.py
from django.db import models

# Create your models here.
# 创建自己的模型

# 自定义管理器类,继承django内部的models.Manager
class BookInfoManager(models.Manager):
    '''
    # 图书模型管理器类
    # 1.自定义all方法，修改原始查询集，重写all()方法
    # 默认查询未删除的图书信息
    # 调用父类的成员语法为：super().方法名
    # BookInfo.objects1.all()
    def all(self):
        return super().all().filter(isDelete=False)

    # 2. 在管理器类中定义创建对象的方法
    # 创建模型类，接收参数为属性赋值
    # 自定义一个创建一个图书对象的方法
    # BookInfo.objects1.create_book("abc",date(1980,1,1))
    def create_book(self, title, pub_date):
        # 创建模型类对象self.model可以自动获得模型类的名称，所以图书类名称变化也可以自动获取
        book = self.model() # book = BookInfo
        book.btitle = title
        book.bpub_date = pub_date
        book.bread = 0
        book.bcommet = 0
        book.isDelete = False
        # 将数据插入进数据表
        book.save()
        return book

    # 定义元选项
    # 在模型类中定义类Meta，用于设置元信息，如使用db_table自定义表的名字。
    # 数据表的默认名称为：
    # appname_modelname
    # booktest_bookinfo
    # class Meta:
        # db_table='bookinfo' #指定BookInfo生成的数据表名为bookinfo,我们也可以自定义其它名称作为model_name
        # 指定BookInfo默认生成的数据表名为bookinfo
        # 相当于使用bookinfo替换默认的名称booktest_bookinfo
        # 好处：即使应用名称改变对表名也没有影响
    '''

# 定义图书模型类BookInfo
class BookInfo(models.Model):
    btitle = models.CharField(max_length=20) # 图书名称
    bpub_date = models.DateField() # 发布日期
    bread = models.IntegerField(default=0) # 阅读量
    bcomment = models.IntegerField(default=0) # 评论量
    isDelete = models.BooleanField(default=False) # 逻辑删除

# 定义英雄模型类HeroInfo
class HeroInfo(models.Model):
    hname = models.CharField(max_length=20) # 英雄姓名
    hgender = models.BooleanField(default=True) # 英雄性别
    isDelete = models.BooleanField(default=False) # 逻辑删除
    hcomment = models.CharField(max_length=200) # 英雄描述信息
    # BookInfo类和HeroInfo类之间具有一对多的关系，这个一对多的关系应该定义在多的那个类，也就是HeroInfo类中
    # 注意设置外键时候django1.8版本以后需要on_delete参数，不然会错误
    hbook = models.ForeignKey('BookInfo', on_delete=models.CASCADE) # 英雄与图书表的关系为一对多，所以属性定义在英雄模型类中


# 定义地区类
class AreaInfo(models.Model):
    atitle = models.CharField(max_length=20) # 地区名称
    aParent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE) # 自关联属性

    # 该魔法方法用于django后台管理, 对象以什么显示，
    # 此处对象设置为以名称显示,admin.py中如果设置对象展示方式list_display，该方法自动忽略
    def __str__(self):
        return self.atitle

    # 自定义title方法，admin.py里面的list_display可以写上面的属性，也可以写方法名称
    def title(self):
        return self.atitle
    # 后台管理可以通过属性点击排序，方法要支持排序，增加下面的排序依据字段
    title.admin_order_field = 'atitle'
    # 指定该方法的在后台中的标题名称，相当于重新命名
    title.short_description = '地区名称'

    # 自定义parent方法
    def parent(self):
        if self.aParent is None:
            return ''
        else:
            return self.aParent.atitle
    parent.short_description = '父级地区名称'
    

# 图片类，用于上传保存图片
class PicTest(models.Model):
    '''上传图片'''
    # upload_to参数就是上传保存图片的文件夹
    # settings里面设置MEDIA_ROOT路径下面的文件夹，一个应用对应自己应用名称的文件夹
    goods_pic = models.ImageField(upload_to='booktest')

03_test4/test4/booktest/views.py
from django.shortcuts import render, redirect
from django.template import loader, RequestContext
from django.http import HttpResponse,JsonResponse
from django.template.context import Context
from booktest.models import BookInfo,PicTest,AreaInfo
from django.conf import settings

# Create your views here.

# 定义一个装饰器，用来判断用户是否已经登录
# view_func就是被装饰的视图函数，*view_args, **view_kwargs是视图函数的位置参数和关键字参数
def login_required(view_func):
    '''登陆判断装饰器'''
    def wrapper(request, *view_args, **view_kwargs):
        # 判断用户是否已经登录
        if request.session.has_key('islogin'):
            # 用户已经登录，调用对应视图函数
            return view_func(request, *view_args, **view_kwargs)
        else:
            # 用户未登录跳转到首页
            return redirect('/login')
    return wrapper


# 模板使标准步骤演示
# 用于处理该url请求：http://127.0.0.1:8000/index
def index(request):
    # 1.加载模板文件(loader.get_template)，获取模板文件的内容，获取一个模板对象
    temp = loader.get_template('booktest/index.html')  # 文件夹路径是templates下开始
    # 2.定义模板上下文(RequestContext),给模板文件传递数据
    # context = RequestContext(request, {})
    # 由于版本更新问题，新的版本context必须是一个字典对象，就是要传递给模板的参数,没有参数就是空
    context = {}
    # 3.模板渲染产生html页面内容 render, 用传递的数据替换相应的变量，产生一个替换后的标准的html内容
    res_html = temp.render(context)
    # 4.返回内容给浏览器
    return HttpResponse(res_html)

    # 上面4步由于版本升级问题，在第3步报错，传入的context必须是字典对象不能是RequestContext对象
    # 参考网址：https://www.cnblogs.com/xiyu714/p/9091619.html

    # 上面4步可以直接进行以下简写，django已经封装好了一个render方法
    # 上面四步也可以定义为一个my_render方法,查看下面
    # return render(request, 'booktest/index.html', {})

def my_render(request, template_path, context={}):
    temp = loader.get_template('booktest/index.html')  # 文件夹路径是templates下开始
    context = {}
    res_html = temp.render(context)
    return HttpResponse(res_html)

# 用于处理该url请求：http://127.0.0.1:8000/index1
def index1(request):
    return my_render(request, 'booktest/index.html')

# 模板标签使用
# 用于处理该url请求：http://127.0.0.1:8000/temp_tags
def temp_tags(request):
    '''模板标签'''
    # 1. 获取所有图书,通过模型类查询
    books = BookInfo.objects.all()
    return render(request, 'booktest/temp_tags.html', {'books': books})

# 模板继承
# 用于处理该url请求：http://127.0.0.1:8000/temp_inherit
def temp_inherit(request):
    '''模板继承'''
    return render(request, 'booktest/child.html')

# 模板转义
# 用于处理该url请求：http://127.0.0.1:8000/temp_escape
def temp_escape(request):
    '''模板转义'''
    content = {'content': '<h1>Hello World</h1>'}
    return render(request, 'booktest/temp_escape.html', content)

# 用于处理该url请求：http://127.0.0.1:8000/login
def login(request):
    '''显示登录页面'''
    # 判断用户是否已经登录过
    if request.session.has_key('islogin'):
        # 用户已经登录过，直接跳转到登录后页面，即跳转到index
        # return redirect('/index')
        # 跳转到修改密码页面
        return redirect('/change_pwd')
    else:
        # 用户未登录，执行下面操作，检测cookie中是否有用户名，有的话自动填写没有就是空
        # 获取cookie值中的username
        if 'username' in request.COOKIES:
            # 访问页面时候，读取浏览器保存的cookie信息，获取里面已经保存的用户名
            username = request.COOKIES.get('username')
        else:
            username = ''
        # 将获取到的username传递给前端html页面，传递给input框的username的值中
        return render(request, 'booktest/login.html', {'username': username})

# 用于处理该url请求：http://127.0.0.1:8000/login_check
def login_check(request):
    # 1.获取提交的用户名和密码
    # print(type(request.POST)) # 查看django服务器终端，里面输出了 <class 'django.http.request.QueryDict'>
    # 获取html页面input表单name属性对应标签输入的值
    username = request.POST.get('username')
    password = request.POST.get('password')
    remember = request.POST.get('remember') # 如果勾选记住用户名选框，remember的值是on

    # 2.进行登陆的校验
    # 实际开发：根据用户名和密码查找数据库，进行匹配
    # 比如： smart 123456
    if username == 'smart' and password == '123456':
        # 用户名和密码正确，跳转到一个页面，此处用首页
        # response = redirect('/index') # redirect是HttpResponseRedirect的简写
        # 跳转到修改密码修改页面
        response = redirect('/change_pwd')

        # 同时继续判断是否需要记住用户名
        if remember == 'on':
            # 设置用户名作为cookie值，设置过期时间为1周,登陆一次再登陆，就提取cookie里面的用户名
            response.set_cookie('username', username, max_age=7*24*3600)

        # 6.16节案例，设置session一个islogin的值，用于记住登陆状态
        # 只要session中有islogin即可，具体设置什么值不重要，此处直接设置值为True
        request.session['islogin'] = True
        # 记录用户的登录名
        request.session['username'] = username
        return response # return要放在if记住用户名同级，如果不勾选也是直接正常登陆
    else:
        # 用户名和密码错误，跳转到登陆页面
        return redirect('/login')

    # 3.返回结果
    # return HttpResponse('OK')

# 用于处理该url请求：http://127.0.0.1:8000/change_pwd
@login_required
def change_pwd(request):
    '''显示修改密码的页面'''
    # 该网页只有用户已经登录了才能访问，通过session进行判断
    # if not request.session.has_key('islogin'):
    #     return redirect('/login')
    # 上面登陆判断封装在一个装饰器中，直接用装饰器装饰即可
    # 我们将浏览器的cookie清楚，然后再访问该页面，就会自动跳转到login页面
    return render(request, 'booktest/change_pwd.html')


# 用于处理该url请求：http://127.0.0.1:8000/change_pwd_action
@login_required
def change_pwd_action(request):
    '''修改密码处理'''
    # 1.获取输入的新密码和用户名(登陆时候已经保存在session中)
    pwd = request.POST.get('pwd')
    username = request.session.get('username')
    # 2.实际开发中：新密码去修改数据库中的内容...
    # 3.返回一个应答
    return HttpResponse('%s密码已经修改为：%s' %(username, pwd))

# 用于处理该url请求：http://127.0.0.1:8000/url_reverse
def url_reverse(request):
    '''url反向解析'''
    return render(request, 'booktest/url_reverse.html')

# 用于处理该url请求：http://127.0.0.1:8000/show_args/1/2
def show_args(request, a, b):
    '''url反向解析,捕获位置参数'''
    return HttpResponse("位置参数分别是：" + a + "和" + b)

# 用于处理该url请求：http://127.0.0.1:8000/show_kwargs/3/4
def show_kwargs(request, num1, num2):
    '''url反向解析,捕获位置参数'''
    return HttpResponse("关键字参数分别是：" + num1 + "和" + num2)

from django.urls import reverse
# 用于处理该url请求：http://127.0.0.1:8000/test_redirect
def test_redirect(request):
    # 重定向到首页
    # return redirect('/index')
    # 如果大量网页重定向到index，但是index地址发生修改，需要修改大量视图中的重定向地址
    # url反向解析动态生成,此时首页地址会自动根据urls.py里面的配置自动反向解析生成
    url = reverse('booktest:index')
    return redirect(url)

    # 重定向使用位置参数
    #     # /show_args/1/2
    #     # url = reverse('booktest:show_args', args=(1, 2))

    # 重定向使用关键字参数
    # /show_args/3/4
    # url = reverse('booktest:show_args', kwargs={'num1': 3, 'num2': 4})


# 静态文件使用
# 用于处理该url请求：http://127.0.0.1:8000/static_test
def static_test(request):
    '''静态文件使用'''
    return render(request, 'booktest/static_test.html')

# 用于处理该url请求：http://127.0.0.1:8000/index2
# 禁止访问单个网址
EXCLUDE_IPS = ['127.0.0.1']
def index2(request):
    '''首页2'''
    # 浏览器用户的ip地址
    user_ip = request.META['REMOTE_ADDR']
    # 本地访问就是127.0.0.1
    print(user_ip)
    # 可以设置禁止访问的IP地址
    if user_ip in EXCLUDE_IPS:
        return HttpResponse('<h1>用户IP禁止访问</h1>')
    else:
        return render(request, 'booktest/index2.html')

# 用于处理该url请求：http://127.0.0.1:8000/index3
def index3(request):
    '''首页3'''
    print('-----index3-----')
    return render(request, 'booktest/index3.html')

# 上传保存图片
# 用于处理该url请求：http://127.0.0.1:8000/pic_upload
def pic_upload(request):
    '''上传图片页面'''
    return render(request,'booktest/pic_upload.html')

# 用于处理该url请求：http://127.0.0.1:8000/pic_handle
def pic_handle(request):
    '''用于接收表单提交的图片保存图片'''
    # request对象的FILES属性用于接收请求的文件，包括图片

    # 1.获取表单上传的图片，获取上传文件的处理对象
    # pic是input的文件类型表单name属性的值
    f1=request.FILES.get('pic')

    # 2.创建文件保存路径
    fname='%s/booktest/%s' % (settings.MEDIA_ROOT, f1.name)

    # 3.打开文件写入上传文件的内容
    # 打开文件已二进制方式写入
    with open(fname,'wb') as pic:
        # f1.chunks()返回文件的一块内容，循环遍历获取所有内容
        for c in f1.chunks():
            pic.write(c)

    # 4.在数据库中保存上传的文件记录
    PicTest.objects.create(goods_pic='booktest/%s' % f1.name)

    # 5.返回内容
    return HttpResponse('OK,图片上传完成！')


# 分页显示地区内容
# 用于处理该url请求：http://127.0.0.1:8000/show_area/1
# pageindex 是url地址传递过来的页码参数
from django.core.paginator import Paginator
def show_area(request, pageindex):
    '''分页显示地区信息'''
    # 1.查出所有省级地区信息,省份的aParent_id的值为NULL,具体查看mysql数据表,可以简写为aParent__isnull=True
    areas = AreaInfo.objects.filter(aParent_id__isnull=True)
    # 2.分页，每页显示5条，返回Paginator类的实例对象paginator(名称自定义)
    paginator = Paginator(areas, 5)
    # 3.获取某一页的内容
    if pageindex == '':
        # 没有指定页码，获取第一页内容
        # 访问：http://127.0.0.1:8000/show_area/
        pageindex = 1
        # 注意：下面的page是Page类的实例对象，即具体某一页内容的实例对象
        # 调用Paginator实例对象即paginator的page()方法返回Page实例对象即page
        # paginator是所有分页内容的实例对象，取出某一页，得到page实例对象
        # page有很多属性，具体查看笔记里面内容和show_area.html代码
        page = paginator.page(pageindex)
    else:
        pageindex = int(pageindex)
        page = paginator.page(int(pageindex))

    # 4.使用模板
    return render(request, 'booktest/show_area.html',
                  {'areas': areas, 'page': page})


# 省市区选择
# 用于处理该url请求：http://127.0.0.1:8000/areas
def areas(request):
    '''省市区选择'''
    return render(request, 'booktest/areas.html')

# 用于处理该url请求：http://127.0.0.1:8000/prov
def prov(request):
    '''获取所有省级地区信息'''
    # 1.获取所有省级地区信息
    areas = AreaInfo.objects.filter(aParent__isnull=True)

    # 2.areas是一个查询集QuerySet,转换为json数据
    areas_list = []
    for area in areas:
        areas_list.append((area.id, area.atitle))
    # print(areas_list)
    # 下面返回为json数据时候，元组自动转变为列表，可以查看网址请求后的原始数据

    # 3.返回数据，HTML发过来是ajax请求，返回数据是json数据
    # areas是一个查询集QuerySet
    return JsonResponse({'data': areas_list})

# 市 县级 地区选择
# 用于处理该url请求：http://127.0.0.1:8000/city/pid 或者http://127.0.0.1:8000/dis/pid
def city(request, pid):
    '''获取省(pid)下级市级信息'''
    # 1.获取pid对应的下级市的信息
    # 方式1：
    # area = AreaInfo.objects.get(id=pid)
    # areas = area.areainfo_set.all()
    # 方式2：
    # 根据父级ID查询下级地区信息
    areas = AreaInfo.objects.filter(aParent__id=pid)

    # 2.变量areas并拼接出json数据：areas是一个查询集QuerySet,转换为json数据
    areas_list = []
    for area in areas:
        areas_list.append((area.id, area.atitle))

    # 3.返回数据，HTML发过来是ajax请求，返回数据是json数据
    # areas是一个查询集QuerySet
    return JsonResponse({'data': areas_list})

03_test4/test4/templates/booktest/areas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>省市区列表</title>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
    <script type="text/javascript">

        $(function () {
            // 打开网页时候发起一个ajax请求，请求地址 /prov 获取省级信息
            // 获取信息，使用get
            // 涉及到信息修改，使用post
            $.get('/prov', function (data) {
                // 回调函数
                // 获取返回的json数据，省级信息的id和atitle
                res = data.data;
                // 获取prov下拉列表框
                prov = $('#prov');
                // 获取每一个元素[地区id, 地区标题]，将省级信息添加到选项框中
                /*for(i=0; i<res.length; i++) {
                    id = res[i][0];
                    atitle = res[i][1];

                    option_str = '<option value="' + id + '">' + atitle + '</option>';
                    // 向下拉列表框中添加省级信息
                    prov.append(option_str);

                }*/

                // 上面for循环遍历可以使用下面each进行遍历
                // 依次操作res里面的每一个元素，item就是res里面的每一个元素
                $.each(res, function (index, item) {
                    id = item[0];
                    atitle = item[1];
                    option_str = '<option value="' + id + '">' + atitle + '</option>';
                    // 向下拉列表框中添加省级信息
                    prov.append(option_str);
                })


            });


            // 绑定prov下拉列表框的change事件，获取省级下面市级信息
            $('#prov').change(function () {
                // 发起一个ajax请求，请求 /city/prov_id 获取省下面市级地区的信息
                // 获取当前选择省份的id，this表示当前选择的元素，val()取出y元素的id值
                prov_id = $(this).val();
                $.get('/city/' + prov_id, function (data) {
                    // 回调函数
                    // 获取返回的json数据，市级信息的id和atitle
                    res = data.data;
                    // 获取prov下拉列表框
                    city = $('#city');
                    // 清空city下拉框内容，因为后面使用的添加，下拉框会不断添加已经查询过的省级下面的市区信息
                    city.empty().append('<option value="">请选择市</option>');
                    // 依次操作res里面的每一个元素，item就是res里面的每一个元素
                    $.each(res, function (index, item) {
                        id = item[0];
                        atitle = item[1];
                        option_str = '<option value="' + id + '">' + atitle + '</option>';
                        // 向下拉列表框中添加市级信息
                        city.append(option_str);
                    })
                });
            });


            // 绑定city下拉列表框的change事件，获取市级下面县级信息
            $('#city').change(function () {
                // 发起一个ajax请求，请求 /city/prov_id 获取省下面市级地区的信息
                // 获取当前选择省份的id，this表示当前选择的元素，val()取出y元素的id值
                city_id = $(this).val();
                $.get('/dis/' + city_id, function (data) {
                    // 回调函数
                    // 获取返回的json数据，市级信息的id和atitle
                    res = data.data;
                    // 获取prov下拉列表框
                    dis = $('#dis');
                    // 清空city下拉框内容，因为后面使用的添加，下拉框会不断添加已经查询过的市级下面的区县信息
                    dis.empty().append('<option value="">请选择区县</option>');
                    // 依次操作res里面的每一个元素，item就是res里面的每一个元素
                    $.each(res, function (index, item) {
                        id = item[0];
                        atitle = item[1];
                        option_str = '<option value="' + id + '">' + atitle + '</option>';
                        // 向下拉列表框中添加市级信息
                        dis.append(option_str);
                    })
                });
            });



        })

    </script>
</head>
    <body>
        <select id="prov">
            <option value="">请选择省</option>
        </select>
        <select id="city">
            <option value="">请选择市</option>
        </select>
        <select id="dis">
            <option value="">请选择区县</option>
        </select>
    </body>
</html>

03_test4/test4/templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>父模板文件</title>
</head>
<body>
    <h1>导航条信息</h1>
    <!--父模板预留位置，用于子模板重新预留块里面的内容-->
    {% block b1 %}
    预留区域，可以编写默认内容，也可以没有默认内容,子模板重写，该父模板内容就直接被覆盖
    {% endblock b1 %}
    <h1>版权信息</h1>
</body>
</html>

03_test4/test4/templates/booktest/change_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码页面</title>
</head>
<body>
    <form method="post" action="/change_pwd_action">
        {% csrf_token %}
        新密码：<input type="password" name="pwd">
        <input type="submit" value="确认修改"> <!--value值就是input框里面填写的值 -->
    </form>
</body>
</html>

03_test4/test4/templates/booktest/child.html
{% extends 'booktest/base.html' %}
{% block b1 %}
<h5>实际填充内容,下面一行是获取的父模板的内容：</h5>
<h6>{{block.super}}用于获取父模板中block中写的内容</h6>
{% endblock b1 %}

03_test4/test4/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <div>tes4项目的首页内容</div>
</body>
</html>

03_test4/test4/templates/booktest/url_reverse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>url反向解析</title>
</head>
<body>
index的普通固定链接：
<a href="/index">首页</a><br/>
index使用url反向解析生成的连接：
<a href="{% url 'booktest:index' %}">首页</a><br/>
访问show_args/1/2固定连接：<br/>
<a href="/show_args/1/2">/show_args/1/2</a><br/>
访问show_args/1/2的url反向解析生成的连接：<br/>
<a href="{% url 'booktest:show_args' 1 2 %}">/show_kwargs/3/4</a><br/>
访问show_kwargs/3/4固定连接：<br/>
<a href="/show_kwargs/3/4">/show_kwargs/3/4</a><br/>
访问show_kwargs/3/4的url反向解析生成的连接：<br/>
<a href="{% url 'booktest:show_kwargs' num1=3 num2=4 %}">/show_kwargs/3/4</a><br/>
</body>
</html>